# Generated by Django 4.2 on 2023-06-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrador", "0002_rename_account_administrador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrador",
            name="avatar",
            field=models.ImageField(
                blank=True, default="usuario.png", null=True, upload_to="avatares"
            ),
        ),
    ]
