# Generated by Django 4.2 on 2023-07-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrador", "0004_alter_administrador_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrador",
            name="avatar",
            field=models.ImageField(
                blank=True, default="usuario.png", null=True, upload_to="avatares"
            ),
        ),
    ]
