# Generated by Django 4.2 on 2023-06-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operario",
            name="imagen",
            field=models.ImageField(default="operario.png", upload_to="operaios"),
        ),
    ]
