# Generated by Django 4.2 on 2023-06-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operario", "0003_alter_operario_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operario",
            name="imagen",
            field=models.ImageField(
                blank=True, default="operario.png", null=True, upload_to="operarios"
            ),
        ),
    ]
