# Generated by Django 4.2 on 2023-06-30 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operario", "0007_alter_operario_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operario",
            name="imagen",
        ),
    ]
