# Generated by Django 4.2 on 2023-06-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operario", "0008_remove_operario_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="operario",
            name="imagen",
            field=models.ImageField(
                blank=True, default="operario.png", null=True, upload_to="operarios"
            ),
        ),
    ]
