# Generated by Django 4.2 on 2023-06-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designacion", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Descripción breve del Producto", max_length=200
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(help_text="Ingrese la cantidad del producto"),
                ),
                (
                    "unidad",
                    models.CharField(
                        default="c/u",
                        help_text="Ingrese la unidad(Ej: Kg, m, Lts)",
                        max_length=10,
                    ),
                ),
                ("vencimiento", models.DateField(blank=True, null=True)),
                ("lote", models.CharField(max_length=30)),
            ],
        ),
    ]
