# Generated by Django 4.2 on 2023-06-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumible", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumible",
            name="especificacion",
            field=models.TextField(
                blank=True,
                help_text="Especificaciones Técnicas del Producto(Data Sheet)",
            ),
        ),
        migrations.AlterField(
            model_name="consumible",
            name="vencimiento",
            field=models.DateField(
                blank=True, help_text="Formato mm/dd/aaaa", null=True
            ),
        ),
    ]
