# Generated by Django 4.2 on 2023-06-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumible", "0002_consumible_especificacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumible",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="fotos"),
        ),
    ]
