# Generated by Django 4.2 on 2023-06-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumible", "0003_consumible_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumible",
            name="imagen",
            field=models.ImageField(default="consumible.png", upload_to=""),
        ),
    ]
