# Generated by Django 4.2 on 2023-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumible", "0005_alter_consumible_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumible",
            name="descripcion",
            field=models.CharField(
                help_text="Descripción breve del Producto",
                max_length=200,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="consumible",
            name="designacion",
            field=models.CharField(
                help_text="Nombre comercial del producto",
                max_length=50,
                verbose_name="Designación",
            ),
        ),
        migrations.AlterField(
            model_name="consumible",
            name="especificacion",
            field=models.TextField(blank=True, help_text="(Data Sheet info)"),
        ),
    ]
