# Generated by Django 4.2 on 2023-06-20 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Herramienta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designacion", models.CharField(max_length=50)),
                ("rastreo", models.IntegerField(help_text="Número de Rastreo")),
                (
                    "asignado",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de asignación al Operario",
                        null=True,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "calibracion",
                    models.DateField(
                        blank=True, help_text="Fecha de calibración", null=True
                    ),
                ),
                (
                    "operario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operario.operario",
                    ),
                ),
            ],
        ),
    ]
