# Generated by Django 4.2 on 2023-06-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("operario", "0001_initial"),
        ("herramienta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herramienta",
            name="operario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="herramientas",
                to="operario.operario",
            ),
        ),
    ]
