# Generated by Django 4.2 on 2023-06-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herramienta", "0002_alter_herramienta_operario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herramienta",
            name="asignado",
            field=models.DateField(
                auto_now=True, help_text="Formato = mm/dd/aaaa", null=True
            ),
        ),
        migrations.AlterField(
            model_name="herramienta",
            name="calibracion",
            field=models.DateField(
                blank=True,
                help_text="Fecha de calibración. Formato = mm/dd/aaaa",
                null=True,
            ),
        ),
    ]
