# Generated by Django 4.2 on 2023-06-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herramienta", "0004_alter_herramienta_calibracion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herramienta",
            name="imagen",
            field=models.ImageField(default="herraienta.png", upload_to="herramientas"),
        ),
    ]
