# Generated by Django 4.2 on 2023-06-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herramienta", "0008_alter_herramienta_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herramienta",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="herramienta.png",
                null=True,
                upload_to="herramientas",
            ),
        ),
    ]
