# Generated by Django 4.2 on 2023-06-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herramienta", "0009_alter_herramienta_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herramienta",
            name="imagen",
        ),
        migrations.AlterField(
            model_name="herramienta",
            name="calibracion",
            field=models.DateField(
                blank=True,
                help_text="Fecha de calibración. Formato = mm/dd/aaaa",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="herramienta",
            name="descripcion",
            field=models.TextField(),
        ),
    ]
