# Generated by Django 4.2 on 2023-06-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herramienta", "0010_remove_herramienta_imagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herramienta",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="herramienta.png",
                null=True,
                upload_to="herramientas",
            ),
        ),
    ]
