# Generated by Django 4.2 on 2023-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herramienta", "0011_herramienta_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herramienta",
            name="calibracion",
            field=models.DateField(
                blank=True,
                help_text="Fecha de calibración. Formato = mm/dd/aaaa",
                null=True,
                verbose_name="Calibración",
            ),
        ),
        migrations.AlterField(
            model_name="herramienta",
            name="descripcion",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="herramienta",
            name="designacion",
            field=models.CharField(max_length=50, verbose_name="Designación"),
        ),
        migrations.AlterField(
            model_name="herramienta",
            name="rastreo",
            field=models.IntegerField(help_text="Número de identificación"),
        ),
    ]
