# Generated by Django 4.2 on 2023-07-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herramienta", "0012_alter_herramienta_calibracion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herramienta",
            name="calibracion",
            field=models.DateField(
                blank=True,
                help_text="Fecha de calibración. Formato = dd/mm/aaaa",
                null=True,
                verbose_name="Calibración",
            ),
        ),
    ]
