# Generated by Django 4.2 on 2023-06-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Encargado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                ("apellido", models.CharField(max_length=60)),
                ("legajo", models.IntegerField()),
                ("sector", models.CharField(max_length=100)),
                ("funcion", models.CharField(max_length=100)),
            ],
        ),
    ]
