# Generated by Django 4.2 on 2023-06-20 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("encargado", "0002_encargado_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encargado",
            name="avatar",
        ),
    ]
