# Generated by Django 4.2 on 2023-06-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encargado", "0005_encargado_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encargado",
            name="imagen",
            field=models.ImageField(
                blank=True, default="encargado.png", null=True, upload_to=""
            ),
        ),
    ]
