# Generated by Django 4.2 on 2023-06-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encargado", "0006_alter_encargado_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encargado",
            name="imagen",
            field=models.ImageField(default="encargado.png", upload_to=""),
        ),
    ]
