# Generated by Django 4.2 on 2023-06-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encargado", "0010_alter_encargado_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encargado",
            name="imagen",
        ),
        migrations.AlterField(
            model_name="encargado",
            name="funcion",
            field=models.CharField(max_length=100),
        ),
    ]
