# Generated by Django 4.2 on 2023-06-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encargado", "0011_remove_encargado_imagen_alter_encargado_funcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="encargado",
            name="imagen",
            field=models.ImageField(
                blank=True, default="encargado.png", null=True, upload_to="encargados"
            ),
        ),
    ]
